# N=int(input("enter the no:"))
# for i in range(10,0,-1):
#     print(f"{N} X {i} = {N*i}")
#     i+=1

#ODD OR EVEN 

# for i in range(0,N+1,2):
#     print(i) #0,1,2,3,4,5{step 2}


# for i in range(1,N+1,2): #prit odd {1,2,3,4,5}
#     print(i)

 # FOR LOOP IN ITERABLE

#LIST string tupke range
# l1=["apple","mango","banana","graps"]
# for i in l1:
#     print(i,end=" ")

#DICTIONARY
d1={
    "name":"gowda","age":23,"loc":"banglore"

}
# for i in d1.keys():
# for i in d1.values():
# for i in d1.items(): #PRINT IN TUPLE
# for i, j in d1.items():
#     print(i,j)

#range
# for i in range(10,0,-2):#start stop step
#     print(i)

# for i in range(0,5,-1):#backwods
#     print(i)#  print ntg  





