# # ARTHMATIC
# a=10
# b=2
# print(a+b)#12
# print(a-b)#8
# print(a*b)#20
# print(a/b)#quatient(5.0)
# print(a%b)#reminder#(0)
# print(a//b)#get whole no(5)
# print(a**b)# square(100)


# #RELATION OR COMPARISION
# num1=10
# num2=20
# print(num1>num2)#false
# print(num1>=num2)#false
# print(num1<num2)#true
# print(num1<=num2)#trute
# print(num1==num2)#false
# print(num1!=num2)#true

# logical operator

#and(both con true)
# n1=10
# n2=40
# print(n1>n2) and(n1<n2)#false
# print(n1<n2)and(n2>n1)# true

#OR(1 CON TRUE= TRUE)
# print(n1<n2) or (n1>n2) #TRUE
# print(n1>n2) or (n2<n1)# false

#NOT {1 CON}{REVERSE}
# print(not(n1<n2))#true but give false

#ASSIGNMENT 

a=20

a+=2 #22
a-=6#16
a*=2#32
a/=6
a%=4
a//=25
print(a)







