#SEARCHIGN AND INFORMATION

#INDEX
# L1=["hello", "hio", "hio",1,2,[1,2,3], True]
# print(L1.index("hio"))# at what index the val is presnt

# #COUNT () THE OCC OF LIST
# print(L1.count("hio"))

#sort[posibel in 1 datatype]
# l2=[10,4,65,76,875]
# l2.sort()
# print(l2)#sort acc
#  #decc
# l2.sort(reverse= True)
# print(l2)



#TUPLESSS

# t1=("hello",6,55,6, True,55)
# print(t1)
# print(type(t1))

# print(t1.count(6))
# print(t1.index("hello"))


